# Uncomment the next line to define a global platform for your project
platform :ios, '10.3'
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

target 'BookingComponent' do
    
pod 'SwiftyUserDefaults'
pod 'CalendarKit'

#UI
pod 'SnapKit', '~> 4.0.0'

#temp
pod 'Eureka'

 target 'BookingComponentTests' do
#    use_frameworks!
    inherit! :search_paths
    pod 'Quick'
    pod 'Nimble', '~> 7.0.2'
  end

end
