//
//  UIColor+CMPAdditions.swift
//
//  Generated by Zeplin on 1/18/18.
//  Copyright (c) 2018 ANODA. All rights reserved. 
//

import UIKit

extension UIColor {
	@nonobjc class var cmpMidGreen: UIColor { 
		return UIColor(red: 76.0 / 255.0, green: 175.0 / 255.0, blue: 80.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var cmpPaleGrey: UIColor { 
		return UIColor(red: 225.0 / 255.0, green: 231.0 / 255.0, blue: 236.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var cmpGunmetal: UIColor { 
		return UIColor(red: 71.0 / 255.0, green: 79.0 / 255.0, blue: 87.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var cmpPale: UIColor { 
		return UIColor(red: 255.0 / 255.0, green: 224.0 / 255.0, blue: 210.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var cmpDarkPeach: UIColor { 
		return UIColor(red: 237.0 / 255.0, green: 119.0 / 255.0, blue: 105.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var cmpSalmon: UIColor { 
		return UIColor(red: 255.0 / 255.0, green: 129.0 / 255.0, blue: 118.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var cmpSteel60: UIColor { 
		return UIColor(red: 139.0 / 255.0, green: 141.0 / 255.0, blue: 145.0 / 255.0, alpha: 0.6)
	}

	@nonobjc class var cmpCoolGrey: UIColor { 
		return UIColor(red: 165.0 / 255.0, green: 173.0 / 255.0, blue: 180.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var cmpWarmGrey: UIColor { 
		return UIColor(white: 158.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var cmpPaleGreyTwo: UIColor { 
		return UIColor(red: 228.0 / 255.0, green: 230.0 / 255.0, blue: 234.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var cmpPaleGreyThree: UIColor { 
		return UIColor(red: 245.0 / 255.0, green: 247.0 / 255.0, blue: 248.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var cmpShamrock: UIColor { 
		return UIColor(red: 0.0, green: 179.0 / 255.0, blue: 65.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var cmpMidGreen75: UIColor { 
		return UIColor(red: 76.0 / 255.0, green: 175.0 / 255.0, blue: 80.0 / 255.0, alpha: 0.75)
	}
    
    @nonobjc class var cmpBrownishOrange5: UIColor {
        return UIColor(red: 222.0 / 255.0, green: 110.0 / 255.0, blue: 39.0 / 255.0, alpha: 0.05)
    }
    
    @nonobjc class var cmpSilver: UIColor {
        return UIColor(red: 234.0 / 255.0, green: 235.0 / 255.0, blue: 236.0 / 255.0, alpha: 1.0)
    }
}
